# Generated by Django 3.2 on 2022-01-26 12:04

from django.db import migrations, models
import uuidapi.models


class Migration(migrations.Migration):

    dependencies = [
        ('uuidapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UUID',
            fields=[
                ('_id', models.UUIDField(default=uuidapi.models.hex_uuid, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Data',
        ),
    ]
